# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-20 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carceropolis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialista',
            name='mini_bio',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
