# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-04 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0001_initial'),
        ('carceropolis', '0002_unidadeprisional'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadeprisional',
            name='municipio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cidades.Cidade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unidadeprisional',
            name='ddd',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='unidadeprisional',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
