# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-20 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carceropolis', '0002_auto_20170220_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialista',
            name='telefone',
        ),
    ]
