# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-04 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carceropolis', '0003_auto_20161004_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadeprisional',
            name='numero',
            field=models.IntegerField(blank=True),
        ),
    ]
