# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-21 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carceropolis', '0004_auto_20170220_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadeprisional',
            name='tipo_logradouro',
            field=models.CharField(max_length=20),
        ),
    ]
