# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-06 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carceropolis', '0004_auto_20161004_0207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areadeatuacao',
            options={'verbose_name': '\xc1rea de Atua\xe7\xe3o', 'verbose_name_plural': '\xc1reas de Atua\xe7\xe3o'},
        ),
        migrations.AlterModelOptions(
            name='especialidade',
            options={'verbose_name': 'Especialidade', 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='especialista',
            options={'verbose_name': 'Especialista', 'verbose_name_plural': 'Especialistas'},
        ),
        migrations.AlterModelOptions(
            name='publicacao',
            options={'verbose_name': 'Publica\xe7\xe3o', 'verbose_name_plural': 'Publica\xe7\xf5es'},
        ),
        migrations.AlterModelOptions(
            name='unidadeprisional',
            options={'verbose_name': 'Unidade Prisional', 'verbose_name_plural': 'Unidades Prisionais'},
        ),
        migrations.AddField(
            model_name='publicacao',
            name='autoria',
            field=models.CharField(default='Diego', max_length=150),
            preserve_default=False,
        ),
    ]
