# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-18 15:01
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carceropolis', '0005_auto_20161106_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='areadeatuacao',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='slugatuacao', editable=False, populate_from=b'nome_da_area'),
            preserve_default=False,
        ),
    ]
