# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-21 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carceropolis', '0005_auto_20170221_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadeprisional',
            name='ddd',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'DDD'),
        ),
        migrations.AlterField(
            model_name='unidadeprisional',
            name='telefone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
