# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-18 15:14
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carceropolis', '0006_areadeatuacao_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areadeatuacao',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from=b'nome_da_area'),
        ),
    ]
