# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-18 15:16
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carceropolis', '0007_auto_20161118_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidade',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='123', editable=False, populate_from=b'nome_da_especialidade'),
            preserve_default=False,
        ),
    ]
