# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-17 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carceropolis', '0009_auto_20161203_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialidade',
            name='nome_da_especialidade',
        ),
        migrations.AddField(
            model_name='especialidade',
            name='nome',
            field=models.CharField(default='Nome da especialidade', max_length=80, unique=True, verbose_name=b'Nome da especialidade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='areadeatuacao',
            name='descricao',
            field=models.TextField(verbose_name=b'Descri\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='areadeatuacao',
            name='nome_da_area',
            field=models.CharField(max_length=250, unique=True, verbose_name=b'Nome da \xc3\xa1rea'),
        ),
        migrations.AlterField(
            model_name='areadeatuacao',
            name='ordem',
            field=models.IntegerField(unique=True, verbose_name=b'Ordem'),
        ),
        migrations.AlterField(
            model_name='especialidade',
            name='descricao',
            field=models.TextField(blank=True, verbose_name=b'Descri\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='area_de_atuacao',
            field=models.ManyToManyField(to='carceropolis.AreaDeAtuacao', verbose_name=b'\xc3\x81rea de atua\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='instituicao',
            field=models.CharField(max_length=250, verbose_name=b'Institui\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='arquivo_publicacao',
            field=models.FileField(upload_to=b'publicacoes/', verbose_name=b'Arquivo da publica\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='unidadeprisional',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cidades.Cidade', verbose_name=b'Munic\xc3\xadpio'),
        ),
        migrations.AlterField(
            model_name='unidadeprisional',
            name='numero',
            field=models.IntegerField(blank=True, verbose_name=b'N\xc3\xbamero'),
        ),
    ]
