# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-31 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carceropolis', '0010_auto_20161230_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areadeatuacao',
            old_name='nome_da_area',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='especialidade',
            old_name='nome_da_especialidade',
            new_name='nome',
        ),
    ]
