# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-17 13:32
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carceropolis', '0010_auto_20161217_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areadeatuacao',
            old_name='nome_da_area',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='areadeatuacao',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from=b'nome'),
        ),
        migrations.AlterField(
            model_name='especialidade',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from=b'nome'),
        ),
    ]
