# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-06 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carceropolis', '0012_auto_20170102_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadeprisional',
            name='numero',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'N\xc3\xbamero'),
        ),
    ]
