# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-19 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carceropolis', '0011_auto_20180728_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areadeatuacao',
            name='descricao_en',
        ),
        migrations.RemoveField(
            model_name='areadeatuacao',
            name='nome_en',
        ),
    ]
