# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-06 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('carceropolis', '0008_auto_20180212_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosEncarceramento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=4)),
                ('mes', models.CharField(max_length=2)),
                ('dados', django_extensions.db.fields.json.JSONField(default=dict)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carceropolis.UnidadePrisional', verbose_name='Unidade Prisional')),
            ],
        ),
    ]
