# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-06 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carceropolis', '0009_dadosencarceramento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadeprisional',
            name='bairro',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='unidadeprisional',
            name='cep',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='unidadeprisional',
            name='complemento',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='unidadeprisional',
            name='nome_logradouro',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='unidadeprisional',
            name='nome_unidade',
            field=models.CharField(max_length=600, verbose_name='Nome da Unidade'),
        ),
        migrations.AlterField(
            model_name='unidadeprisional',
            name='responsavel',
            field=models.CharField(blank=True, max_length=600, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='unidadeprisional',
            name='sigla_unidade',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='unidadeprisional',
            name='tipo_logradouro',
            field=models.CharField(max_length=600),
        ),
    ]
