# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-06 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carceropolis', '0010_auto_20180706_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadeprisional',
            name='id_2014_06',
        ),
        migrations.RemoveField(
            model_name='unidadeprisional',
            name='id_2014_12',
        ),
        migrations.RemoveField(
            model_name='unidadeprisional',
            name='id_2015_12',
        ),
        migrations.RemoveField(
            model_name='unidadeprisional',
            name='id_2016_06',
        ),
    ]
