# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-07 11:59
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('carceropolis', '0011_auto_20180706_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosencarceramento',
            name='card',
            field=django_extensions.db.fields.json.JSONField(default=dict),
        ),
    ]
