# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('carceropolis_theme', '0001_initial'), ('carceropolis_theme', '0002_remove_especialidades_slug'), ('carceropolis_theme', '0003_auto_20160915_2332'), ('carceropolis_theme', '0004_auto_20160915_2358'), ('carceropolis_theme', '0005_auto_20160916_0004'), ('carceropolis_theme', '0006_auto_20160916_0127'), ('carceropolis_theme', '0007_auto_20160916_1639'), ('carceropolis_theme', '0008_auto_20160920_1020'), ('carceropolis_theme', '0009_especialidade_descricao')]

    initial = True

    dependencies = [
        ('blog', '0002_auto_20150527_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=250)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('instituicao', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('categorias', models.ManyToManyField(help_text=b'Categorias principais da especialidade deste especialista. Escolha uma categoria ao menos.', to=b'carceropolis_theme.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_especialidade', models.CharField(max_length=35)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('blogpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.BlogPost')),
                ('categorias', models.ManyToManyField(help_text=b'Categorias principais da especialidade deste especialista. Escolha uma categoria ao menos.', to=b'carceropolis_theme.Categoria')),
            ],
            options={
                'abstract': False,
            },
            bases=('blog.blogpost',),
        ),
        migrations.AddField(
            model_name='especialista',
            name='especialidades',
            field=models.ManyToManyField(help_text=b'Lista de Especialidades espec\xc3\xadficas deste especialista (separadas por v\xc3\xadrgula)', to=b'carceropolis_theme.Especialidade'),
        ),
    ]
