# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-15 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=250)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(max_length=35)),
                ('slug', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('instituicao', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('categorias', models.ManyToManyField(to='carceropolis_theme.Categoria')),
                ('especialidade', models.ManyToManyField(to='carceropolis_theme.Especialidades')),
            ],
        ),
    ]
