# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carceropolis_theme', '0001_squashed_0009_especialidade_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaDeAtuacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_area', models.CharField(max_length=250)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='especialista',
            name='categorias',
        ),
        migrations.AddField(
            model_name='especialista',
            name='minibio',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='especialista',
            name='telefone',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='especialidades',
            field=models.ManyToManyField(to='carceropolis_theme.Especialidade'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='categorias',
            field=models.ManyToManyField(to='carceropolis_theme.AreaDeAtuacao'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.AddField(
            model_name='especialista',
            name='area_de_atuacao',
            field=models.ManyToManyField(to='carceropolis_theme.AreaDeAtuacao'),
        ),
    ]
