# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carceropolis_theme', '0002_auto_20160920_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialista',
            old_name='minibio',
            new_name='mini_bio',
        ),
    ]
