# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 16:00
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('carceropolis_theme', '0003_auto_20160920_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialista',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
    ]
