# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carceropolis_theme', '0004_auto_20160920_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='areadeatuacao',
            name='ordem',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacao',
            name='arquivo_publicacao',
            field=models.FileField(default='', upload_to=b'publicacoes/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='areadeatuacao',
            name='nome_da_area',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='especialidade',
            name='nome_da_especialidade',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
