# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-29 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carceropolis_theme', '0005_auto_20160920_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacao',
            options={'verbose_name_plural': 'Publica\xe7\xf5es'},
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='arquivo_publicacao',
            field=models.FileField(upload_to=b'publicacoes/', verbose_name=b'Arquivo da Publica\xc3\xa7\xc3\xa3o'),
        ),
    ]
