# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-15 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='value_en',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='value_pt_br',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
