# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-19 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0002_auto_20180715_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='value_en',
        ),
    ]
